# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "webrick", "~> 1.9"

gem "github-pages", "~> 232", :group => :jekyll_plugins

gem "jekyll-autoprefixer", "~> 1.0", :group => :jekyll_plugins

gem "execjs", "= 2.7"
